#This programme asks the user to choose and input 3 numbers and then adds them up and then displays the answer.
import time
number1 = int(input("please enter the first number you want to chose"))
number2 = int(input("please enter the second number"))
number3 = int(input("please enter the third number"))
print("now i will calculate the sum of the numbers please wait 10 seconds for the calculation to be finished")
answer = number1 + number2 + number3
time.sleep(1)
print("10")
time.sleep(1)
print("9")
time.sleep(1)
print("8")
time.sleep(1)
print("7")
time.sleep(1)
print("6")
time.sleep(1)
print("5")
time.sleep(1)
print("4")
time.sleep(1)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)
print("the calculation has finished here is the answer")
print(answer)
              
